# Generated by Django 5.1.3 on 2024-12-01 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('executivename', models.CharField(blank=True, db_column='ExecutiveName', max_length=100, null=True)),
                ('executivetitle', models.CharField(blank=True, db_column='ExecutiveTitle', max_length=200, null=True)),
                ('pk_executive_id', models.AutoField(db_column='PK_Executive_Id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Executive',
            },
        ),
        migrations.CreateModel(
            name='EquityAward',
            fields=[
                ('pk_equityaward_id', models.AutoField(db_column='PK_EquityAward_Id', primary_key=True, serialize=False)),
                ('awardtype', models.CharField(blank=True, db_column='AwardType', max_length=10, null=True)),
                ('awardsgranted', models.IntegerField(blank=True, db_column='AwardsGranted', null=True)),
                ('grantdate', models.DateField(blank=True, db_column='GrantDate', null=True)),
                ('stockprice', models.DecimalField(blank=True, db_column='StockPrice', decimal_places=5, max_digits=10, null=True)),
                ('executive', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.executive')),
            ],
            options={
                'db_table': 'EquityAward',
            },
        ),
    ]
