# Generated by Django 5.1.3 on 2024-12-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equityaward',
            name='stockprice',
            field=models.DecimalField(blank=True, db_column='StockPrice', decimal_places=2, max_digits=18, null=True),
        ),
    ]
