# Generated by Django 5.1.3 on 2024-12-04 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_equityaward_stockprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('companyname', models.CharField(db_column='CompanyName', max_length=200)),
                ('pk_companies_id', models.AutoField(db_column='PK_Companies_Id', primary_key=True, serialize=False)),
                ('ticker', models.CharField(db_column='Ticker', max_length=30)),
            ],
            options={
                'db_table': 'Companies',
            },
        ),
        migrations.AlterField(
            model_name='equityaward',
            name='executive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.executive'),
        ),
        migrations.AddField(
            model_name='executive',
            name='companies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.companies'),
        ),
    ]
